name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x, 21.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: ESLint
              run: npm run eslint
            - name: Prettier
              run: npm run prettier:check
            - name: Build
              run: npm run --if-present build
            - name: Test
              run: npm run --if-present test

    npm-pkg-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: ~/.cache/npm-pkg-lint
                  key: npm-pkg-lint
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run --if-present build
            - name: npm-pkg-lint
              run: |
                  for pkg in packages/*/; do (
                      echo "::group::${pkg}"
                      set -e
                      cd $pkg
                      npm pack
                      npm exec npm-pkg-lint -- --allow-dependency prettier,vue
                      echo "::endgroup::"
                  ); done
