name: Release

on:
    push:
        branches:
            - release/29.x

jobs:
    release:
        name: Release
        uses: Forsakringskassan/.github/.github/workflows/npm-release.yaml@main
        with:
            app-id: ${{ vars.RELEASE_APP_ID }}
        secrets:
            app-key: ${{ secrets.RELEASE_APP_KEY }}
